### ISSUE TITLE
缺少必要文件

### ISSUE THREAD

**Issue by SunHui1216** [Nathan-Li123/SMOTer#1]
![Screenshot from 2024-08-06 20-24-36](https://github.com/user-attachments/assets/a363cb68-e1ab-4783-a51c-964bba3d7b8f)
我在配置好环境之后运行代码的时候发现有如下报错并在tao,controlnet代码中均未找到结构相似的文件夹,请问这个这个代码怎么获得呢?

**Comment by Nathan-Li123** [comment]
似乎是文件上传时的问题，我已经更新了仓库，现在应该是可以了。如果不行的话，请check一下这个回答对您是否有帮助：https://stackoverflow.com/questions/59762996/how-to-fix-attributeerror-partially-initialized-module
