### ISSUE TITLE
关于缺少python包

### ISSUE THREAD

**Issue by zhaosonghui** [Nathan-Li123/SMOTer#2]
![1234567](https://github.com/user-attachments/assets/44a646b6-a723-44ca-9fe6-38733f5f2514)

Hi, this is an exciting research project! While running the training command during my floating experiments, I encountered an error stating that the "tao" package is missing. I wanted to ask if you've ever encountered this situation.

**Comment by Nathan-Li123** [comment]
run this: pip install git+https://github.com/TAO-Dataset/tao to install module 'tao'. Alternatively, I believe commenting out that import line should work as well, because our code doesn’t actually use the TAO dataset.

**Comment by zhaosonghui** [comment]
Thank you for your answer!
When reproducing the experiment, I encountered another error. I would like to know if you have encountered this error before
![image](https://github.com/user-attachments/assets/b740b6c8-45e3-44ae-b21b-193602e6671b)

**Comment by Nathan-Li123** [comment]
<img width="258" alt="image" src="https://github.com/user-attachments/assets/14d40516-b3bf-43f8-b0c2-bbd9180d0470">
Download the corresponding files from https://huggingface.co/google-bert/bert-base-uncased/tree/main and place them in the ./bert-base-uncased folder. These are the publicly available weights (from Hugging Face) used for our text head.

**Comment by zhaosonghui** [comment]
Thank you very much for your answer!

As for the dataset, it was processed like this:
![image](https://github.com/user-attachments/assets/f4cc813f-b7ea-45c2-84cd-da2699c088de)
First, create three new folders: annotations, seqmaps, and BenSMOT-val in the specified directory.
Next, run Python tools/convert_bensmot2coco.py to generate train.json and test.json in the annotations folder.
![image](https://github.com/user-attachments/assets/2ca17b40-5572-4f74-b535-837530a92d00)
Then, uncomment the five lines of code in tools/convert_bensmot2coco.py, and run Python tools/convert_bensmot2coco.py to obtain BenSMOT-val.txt in the seqmaps folder.
![image](https://github.com/user-attachments/assets/11614db5-9197-4c03-b885-4085f961c1c2)
Is this method of processing the dataset correct?

**Comment by Nathan-Li123** [comment]
It seems there’s no problem.

**Comment by zhaosonghui** [comment]
Thank you very much for your answer!

**Comment by zhaosonghui** [comment]
I set the batch_size to 1 and ran it on a single GPU, but it seems there are some errors with the processed dataset.
![image](https://github.com/user-attachments/assets/0a7eeddc-7ad4-47b1-8dbd-96395f2edd31)

**Comment by zhaosonghui** [comment]
这是我在“convert_bensmot2coco.py”代码中的设置

![image](https://github.com/user-attachments/assets/23ac35cf-9e3c-4572-b90c-28e124025d73)

![image](https://github.com/user-attachments/assets/b8d29258-b00e-4294-9eea-87ce0f573395)

**Comment by Nathan-Li123** [comment]
你需要修改一下路径，你这里用的是我的路径。需要修改的包括smoter/data/datasets/bensmot.py和smoter/data/smoter_dataset_dataloader.py文件中的路径部分。

**Comment by zhaosonghui** [comment]
![image](https://github.com/user-attachments/assets/1ba60d66-7b5a-4ea3-80bd-e6836a6d3907)
![image](https://github.com/user-attachments/assets/41d70041-5932-4572-89e1-9f2e9a92524b)
在下载的数据集中，训练图片在“BenSMOT/train/talking_with_child/48MtwPnzqQ0_0/imgs/001.jpg”中,而运行代码寻找的路径是“BenSMOT/train/talking_with_child/48MtwPnzqQ0_0/001.jpg”下，比数据集中少一个imgs文件路径，是不是生成的json文件可能有问题？

**Comment by zhaosonghui** [comment]
![image](https://github.com/user-attachments/assets/053a5181-d2f5-4f3f-b90a-51be93126dee)
生成的json文件中，路径好像有点不太对，与实际数据集中文件夹组织结构不一样

**Comment by Nathan-Li123** [comment]
好像是的，你可以直接修改一下convert_bensmot2coco.py的53行。感谢指出，我之后会更新代码仓库。

**Comment by zhaosonghui** [comment]
好的，感谢及时回复！

**Comment by zhaosonghui** [comment]
我用的单卡4090，batch_size设置的是1，进行训练，显示显存不够。想问一下您当时用4卡 V100（32G）显存版本训练的时候，每个GPU大概占用多少显存？

**Comment by Nathan-Li123** [comment]
每张卡接近30G，如果显存不够可以调小每次使用的图像数量（byte_rcnn.py文件内的145和147行）。他应该是超参格式的，这里我暂时还没弄。。

**Comment by zhaosonghui** [comment]
好的，谢谢您！
