### ISSUE TITLE
公布的cfg文件或者checkpoint文件存在问题

### ISSUE THREAD

**Issue by sove45** [Nathan-Li123/SMOTer#3]
作者您好,我遵循github上的教程采样CH_FPN_1x.pth

其中cfg文件内容为
#
_BASE_: "Base-CenterNet.yaml"
MODEL:
  META_ARCHITECTURE: "BYTERCNN"
  CENTERNET:
    USE_DEFORMABLE: True
    NMS_TH_TEST: 0.6
  ROI_HEADS:
    NAME: GRiTROIHeads
    PROPOSAL_APPEND_GT: False
    NO_BOX_HEAD: True
  WEIGHTS: '/15342518312/MOT/wegt/CH_FPN_1x.pth'
  ASSO_ON: True
  ASSO_HEAD:
    NEG_UNMATCHED: True
    ASSO_THRESH: 0.3
    ASSO_THRESH_TEST: 0.55
    ASSO_WEIGHT: 1.0
    NUM_WEIGHT_LAYERS: 0
    NO_POS_EMB: True
SOLVER:
  USE_CUSTOM_SOLVER: True
  MAX_ITER: 70000
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BASE_LR: 0.00005
  OPTIMIZER: ADAMW
  IMS_PER_BATCH: 4
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.1
    NORM_TYPE: 2.0
  BACKBONE_MULTIPLIER: 0.1
  # CUSTOM_MULTIPLIER: 2.0
  # CUSTOM_MULTIPLIER_NAME: ["summary_text_decoder", "classifier"]
INPUT:
  FORMAT: RGB
  CUSTOM_AUG: EfficientDetResizeCrop
  TRAIN_SIZE: 1280
  NOT_CLAMP_BOX: True
  TEST_INPUT_TYPE: square
  TEST_SIZE: 1560
  VIDEO:
    TRAIN_LEN: 100
    TEST_LEN: 100
VIDEO_INPUT: True
VIDEO_TEST:
  MAX_CENTER_DIST: 1.0
  OVERLAP_THRESH: 0.2
  DECAY_TIME: 0.9
  WITH_IOU: True
  NOT_MULT_THRESH: True
DATASETS:
  # TRAIN: ("mot17_halftrain","crowdhuman_train")
  TRAIN: ("bensmot_train",)
  TEST: ("bensmot_val",)
FIND_UNUSED_PARAM: True
DATALOADER:
  SAMPLER_TRAIN: "MultiDatasetSampler"
  SOURCE_AWARE: True
  DATASET_RATIO: [1]
采样的ckeckpoint文件为公开的CH_FPN_1x.pth
但是在测试过程中出现了大量的
WARNING [08/12 07:39:52 fvcore.common.checkpoint]: The checkpoint state_dict contains keys that are not used by the model:
WARNING [08/12 07:39:52 fvcore.common.checkpoint]: Some model parameters or buffers are not found in the checkpoint:
警告,这说明cfg中设置的模型与ckpt文件的模型不相同,
相反在我根据此cfg文件重新训练的模型ckpt文件的时候并没有出现这种情况,这进一步说明了cfg文件与ckpt文件不匹配

**Comment by sove45** [comment]
同样,在利用ckpt文件与公开的cfg文件进行测试的过程中还出现了输出的results, summary, caption, relation均为空集的情况

**Comment by sove45** [comment]
> 同样,在利用ckpt文件与公开的cfg文件进行测试的过程中还出现了输出的results, summary, caption, relation均为空集的情况

我猜测这和cfg文件与ckpt文件不匹配有关

**Comment by Nathan-Li123** [comment]
这是因为CH_FPN_1x.pth只是训练时的用到的只包含部分参数的预训练权重，而不是完整的权重文件。

**Comment by sove45** [comment]
> 这是因为CH_FPN_1x.pth只是训练时的用到的只包含部分参数的预训练权重，而不是完整的权重文件。

好的,非常感谢您的帮助我将带上这些预训练权重来进行训练
