### ISSUE TITLE
训练与测试上的一些问题

### ISSUE THREAD

**Issue by sove45** [Nathan-Li123/SMOTer#4]
您好,我想follow你们的工作,但是我在训练和测试上遇到了一些问题
首先在训练过程中,我将公开的2个预训练的ckpt文件加载到训练模型中,其中cfg文件为
##
_BASE_: "Base-CenterNet.yaml"
MODEL:
  META_ARCHITECTURE: "BYTERCNN"
  CENTERNET:
    USE_DEFORMABLE: True
    NMS_TH_TEST: 0.6
  ROI_HEADS:
    NAME: GRiTROIHeads
    PROPOSAL_APPEND_GT: False
    NO_BOX_HEAD: True
  WEIGHTS: '/15342518312/MOT/output/SMOTer/BYTE_BENSMOT_FPN/model_0024999.pth'
  ASSO_ON: True
  ASSO_HEAD:
    NEG_UNMATCHED: True
    ASSO_THRESH: 0.3
    ASSO_THRESH_TEST: 0.55
    ASSO_WEIGHT: 1.0
    NUM_WEIGHT_LAYERS: 0
    NO_POS_EMB: True
SOLVER:
  USE_CUSTOM_SOLVER: True
  MAX_ITER: 70000
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BASE_LR: 0.00005
  OPTIMIZER: ADAMW
  IMS_PER_BATCH: 4
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.1
    NORM_TYPE: 2.0
  BACKBONE_MULTIPLIER: 0.1
  # CUSTOM_MULTIPLIER: 2.0
  # CUSTOM_MULTIPLIER_NAME: ["summary_text_decoder", "classifier"]
INPUT:
  FORMAT: RGB
  CUSTOM_AUG: EfficientDetResizeCrop
  TRAIN_SIZE: 1280
  NOT_CLAMP_BOX: True
  TEST_INPUT_TYPE: square
  TEST_SIZE: 1560
  VIDEO:
    TRAIN_LEN: 100
    TEST_LEN: 100
VIDEO_INPUT: True
VIDEO_TEST:
  MAX_CENTER_DIST: 1.0
  OVERLAP_THRESH: 0.2
  DECAY_TIME: 0.9
  WITH_IOU: True
  NOT_MULT_THRESH: True
DATASETS:
  # TRAIN: ("mot17_halftrain","crowdhuman_train")
  TRAIN: ("bensmot_train",)
  TEST: ("bensmot_val",)
FIND_UNUSED_PARAM: True
DATALOADER:
  SAMPLER_TRAIN: "MultiDatasetSampler"
  SOURCE_AWARE: True
  DATASET_RATIO: [1]

##
我在一张A800显卡上进行训练
首先进行了一个时长为20h的训练过程之后经历了一个预计需要3天来训练的训练过程(正在进行),在训练过程中我把其中的一个ckpt:/15342518312/MOT/output/SMOTer/BYTE_BENSMOT_FPN/model_0024999.pth拿来测试,然后出现了如下报错
##
Traceback (most recent call last):
  File "/15342518312/MOT/train_net.py", line 301, in <module>
    launch(
  File "/15342518312/MOT/detectron2/detectron2/engine/launch.py", line 84, in launch
    main_func(*args)
  File "/15342518312/MOT/train_net.py", line 276, in main
    return do_test(cfg, model)
  File "/15342518312/MOT/train_net.py", line 129, in do_test
    results[dataset_name], summary[dataset_name], caption[dataset_name], relation[dataset_name] = inference_on_dataset(
ValueError: not enough values to unpack (expected 4, got 0)

Process finished with exit code 1
##
也就是说在整个测试过程中我的输出的result,caption,relation,都是空集
在训练过程中我们的模型占用显存为43.82G>38G
我们希望知道跟多的模型的训练细节,其中包括更详细的模块训练顺序,训练的资源占用与耗时,以及训练的可训练参数,哪些为解冻状态和训练不同阶段的loss构成

**Comment by Nathan-Li123** [comment]
我们使用的四张32GB显存的V100进行的训练，训练时长大约为1-2天。在训练时，前20000个iter只进行检测器的训练，在之后的训练iter中才会开放后续模块（包括video caption、instance caption和relation生成模块）的权重。
你的这个cfg文件看起来似乎没有什么问题。不过你用几张卡跑IMS_PER_BATCH应该要设置成几，但是这不应该会导致测试全部输出空集的问题。

**Comment by zhaosonghui** [comment]
您好，我同样在测试SMOT/output/SMOTer/BYTE_BENSMOT_FPN/model_0034999.pth的时候，出现了这个错误，返回的是空集。
![image](https://github.com/user-attachments/assets/49408f3e-31e0-459e-b625-44000470336b)
