### ISSUE TITLE
关于模型测试为空集的问题

### ISSUE THREAD

**Issue by zhaosonghui** [Nathan-Li123/SMOTer#5]
您好！ 我用单卡A100进行训练，用训练好的模型进行测试，测试命令是：CUDA_VISIBLE_DEVICES=1 python train_net.py --config-file configs/BYTE_BENSMOT_FPN.yaml --eval-only MODEL.WEIGHTS output/SMOTer/BYTE_BENSMOT_FPN/model_0034999.pth

发现测试Inference完成后，返回的结果是空集。
![image](https://github.com/user-attachments/assets/53eafa30-30e0-457f-8930-5921b6c5a0ed)

值得注意的是：单卡训练时，loss_centernet_loc：0, loss_centernet_agn_pos:0。
![image](https://github.com/user-attachments/assets/6e23b184-c75d-44e1-ae39-64190f850817)
想问一下您之前有没有用单卡跑过实验，出现过类似的情况？

在多卡（4卡A100）训练时，loss_centernet_loc和loss_centernet_agn_pos是正常的。目前多卡还没跑出训练模型，还没有测试是否多卡训练出的模型测试也为空集。
![image](https://github.com/user-attachments/assets/eeae5a51-e0c9-4fd3-b473-7587f8c52ba7)

**Comment by zhaosonghui** [comment]
测试完成后好像也没有产生测试结果的文件

**Comment by zhaosonghui** [comment]
在用4卡a100训练，训练过程中各项loss都正常，当训练完成后，利用最后的pth进行测试，结果同样显示为空集。
![image](https://github.com/user-attachments/assets/fc637da2-32bf-4886-97e9-7bd43e3444bb)
![image](https://github.com/user-attachments/assets/c3568b5d-9dbf-4521-9aad-b8307c7e4248)![image](https://github.com/user-attachments/assets/de49d1ba-31ce-489f-aa0e-82c9a8e5bf67)

**Comment by Nathan-Li123** [comment]
损失有问题，这里只有定位的损失，没有后续步骤的额损失，能否看一下byte_rcnn.py文件，是否和目前仓库中的文件版本一致？

**Comment by Nathan-Li123** [comment]
或者给我截个图我看一下

**Comment by zhaosonghui** [comment]
![image](https://github.com/user-attachments/assets/bfe0f225-05d3-4f6b-9197-dc91fff0d31c)
上面是byte_rcnn.py文件路径。下面是byte_rcnn.py的代码，应该是和目前仓库中的保持一致的。
import os
import json
from detectron2.layers.shape_spec import ShapeSpec
from detectron2.modeling.poolers import ROIPooler
import torch
import random
import numpy as np
from scipy.optimize import linear_sum_assignment
import torch.nn.functional as F

from detectron2.config import configurable
from detectron2.structures import Boxes, pairwise_iou, Instances
from detectron2.structures import ImageList
from detectron2.modeling.meta_arch.build import META_ARCH_REGISTRY

from smoter.modeling.roi_heads.association_head import FCHead
from smoter.modeling.roi_heads.grit_roi_heads import get_relation_labels
from .custom_rcnn import CustomRCNN
from ..roi_heads.custom_fast_rcnn import custom_fast_rcnn_inference
from ..tracker.byte_tracker import BYTETracker
from ..tracker.ocsort import OCSort
from ..tracker.sort import Sort


@META_ARCH_REGISTRY.register()
class BYTERCNN(CustomRCNN):
    @configurable
    def __init__(self, **kwargs):
        """
        """
        self.cfg = kwargs.pop('cfg')
        self.test_len = kwargs.pop('test_len')
        self.overlap_thresh = kwargs.pop('overlap_thresh')
        self.min_track_len = kwargs.pop('min_track_len')
        self.max_center_dist = kwargs.pop('max_center_dist')
        self.decay_time = kwargs.pop('decay_time')
        self.asso_thresh = kwargs.pop('asso_thresh')
        self.with_iou = kwargs.pop('with_iou')
        self.local_track = kwargs.pop('local_track')
        self.local_no_iou = kwargs.pop('local_no_iou')
        self.local_iou_only = kwargs.pop('local_iou_only')
        self.not_mult_thresh = kwargs.pop('not_mult_thresh')
        super().__init__(**kwargs)

        self._init_asso_head(self.cfg, self.backbone.output_shape())
        # self._init_feat_loader()


    @classmethod
    def from_config(cls, cfg):
        ret = super().from_config(cfg)
        ret['cfg'] = cfg
        ret['test_len'] = cfg.INPUT.VIDEO.TEST_LEN
        ret['overlap_thresh'] = cfg.VIDEO_TEST.OVERLAP_THRESH     
        ret['asso_thresh'] = cfg.MODEL.ASSO_HEAD.ASSO_THRESH
        ret['min_track_len'] = cfg.VIDEO_TEST.MIN_TRACK_LEN
        ret['max_center_dist'] = cfg.VIDEO_TEST.MAX_CENTER_DIST
        ret['decay_time'] = cfg.VIDEO_TEST.DECAY_TIME
        ret['with_iou'] = cfg.VIDEO_TEST.WITH_IOU
        ret['local_track'] = cfg.VIDEO_TEST.LOCAL_TRACK
        ret['local_no_iou'] = cfg.VIDEO_TEST.LOCAL_NO_IOU
        ret['local_iou_only'] = cfg.VIDEO_TEST.LOCAL_IOU_ONLY
        ret['not_mult_thresh'] = cfg.VIDEO_TEST.NOT_MULT_THRESH
        return ret


    def _init_asso_head(self, cfg, input_shape):
        in_features = cfg.MODEL.ROI_HEADS.IN_FEATURES        
        asso_in_channels = input_shape[in_features[0]].channels
        pooler_resolution = cfg.MODEL.ROI_BOX_HEAD.POOLER_RESOLUTION
        pooler_scales = tuple(1.0 / input_shape[k].stride for k in in_features)  # noqa
        sampling_ratio = cfg.MODEL.ROI_BOX_HEAD.POOLER_SAMPLING_RATIO
        pooler_type = cfg.MODEL.ROI_BOX_HEAD.POOLER_TYPE
        self.asso_pooler = ROIPooler(
            output_size=pooler_resolution,
            scales=pooler_scales,
            sampling_ratio=sampling_ratio,
            pooler_type=pooler_type,
        )
        self.asso_head = FCHead(
            input_shape=ShapeSpec(
                channels=asso_in_channels, 
                height=pooler_resolution, width=pooler_resolution),
            fc_dim=cfg.MODEL.ASSO_HEAD.FC_DIM,
            num_fc=cfg.MODEL.ASSO_HEAD.NUM_FC,
        )

    def _init_feat_loader(self, track_results_path='/data3/motrv2_bensmot_train'):
        with open('datasets/bensmot/instance_caption.json', 'r') as f:
            instance_captions = json.load(f)
        with open('datasets/bensmot/video_summary.json', 'r') as f:
            video_summaries = json.load(f)
        with open('datasets/bensmot/relation.json', 'r') as f:
            relations = json.load(f)
        with open('datasets/bensmot/track_transfer_train.json', 'r') as f:
            transfer = json.load(f)
        gt_seq_names = list(set(instance_captions.keys()) & set(video_summaries.keys()) & set(relations.keys()))
        print('registered %d groundtruth sequences.' % len(gt_seq_names))

        self.video_summaries = video_summaries
        self.instance_captions = instance_captions
        self.instance_ralations = relations
        self.transfer = transfer

        frame_feats, track_embeds = {}, {}
        cate_dirs = os.listdir(track_results_path)
        for cate_dir in cate_dirs:
            cate_dir_path = os.path.join(track_results_path, cate_dir)
            video_dirs = os.listdir(cate_dir_path)
            for video_dir in video_dirs:
                video_dir_path = os.path.join(cate_dir_path, video_dir)
                seq_name = cate_dir + '/' + video_dir 
                frame_feat_path = os.path.join(video_dir_path, 'frame_features.json')
                track_embed_path =os.path.join(video_dir_path, 'track_embeddings.json')
                frame_feats[seq_name] = frame_feat_path
                track_embeds[seq_name] = track_embed_path
        tk_seq_names = list(frame_feats.keys())
        print('registered %d track sequences.' % len(tk_seq_names))
        seq_names = list(set(gt_seq_names) & set(tk_seq_names))
        print('registered %d commen sequences in total.' % len(seq_names))
        seq_names.sort()

        self.frame_feats = frame_feats
        self.track_embeds = track_embeds
        self.seq_names = seq_names
        self.seq_num = len(seq_names)


    def forward(self, batched_inputs, iteration=None):
        """
        All batched images are from the same video
        During testing, the current implementation requires all frames 
            in a video are loaded.
        TODO (Xingyi): one-the-fly testing
        """
        if not self.training:
            return self.local_tracker_inference(batched_inputs)
        assert iteration is not None
        video_info = batched_inputs[-1]
        batched_inputs = batched_inputs[:-1]
        images = self.preprocess_image(batched_inputs)
        gt_instances = [x["instances"].to(self.device) for x in batched_inputs]
        num_images = len(images)
        if iteration >= 20000:
            min_num = 6
        else:
            min_num = 10
        if num_images > min_num:
            idx = random.randint(0, num_images - min_num)
            tmp_images = torch.stack(images.tensor.unbind(0)[idx:idx+min_num])
            tmp_images_sizes = images.image_sizes[idx:idx+min_num]
            tmp_images = ImageList(tmp_images, tmp_images_sizes)
            tmp_batched_inputs = batched_inputs[idx:idx+min_num]
            tmp_gt_instances = [x["instances"].to(self.device) for x in tmp_batched_inputs]

            features = self.backbone(tmp_images.tensor)
            _, proposal_losses = self.proposal_generator(tmp_images, features, tmp_gt_instances)
        else:
            features = self.backbone(images.tensor)
            # gt_instances = [x["instances"].to(self.device) for x in batched_inputs]
            _, proposal_losses = self.proposal_generator(images, features, gt_instances)
        
        losses = {}
        losses.update(proposal_losses)
        
        # strat tracking
        if iteration >= 20000:
            pred_instances, video_features = self.inferene_tracks(batched_inputs)
            # end tracking
            pred_tracks = self._post_process_tracks(pred_instances, gt=False)
            gt_tracks = self._post_process_tracks(gt_instances, gt=True)
            gt_tracks = self._check_gt_tracks(gt_tracks, video_info['caption'])
            transfered_pred_tracks, gt_ids = self._transfer_track_ids(gt_tracks=gt_tracks, pred_tracks=pred_tracks)

            summary_info = [video_info['summary']]
            caption_info = video_info['caption']
            relation_info = video_info['relation']
            
            summary_losses = self.roi_heads({
                'feats': video_features, 'pred_tracks': transfered_pred_tracks, 'gt_ids': gt_ids, \
                'text': summary_info, 'mode': 'summary'
            })
            caption_losses = self.roi_heads({
                'pred_tracks': transfered_pred_tracks, 'gt_ids': gt_ids, \
                'texts': caption_info, 'mode': 'caption'
            })
            relation_losses = self.roi_heads({
                'pred_tracks': transfered_pred_tracks, 'gt_ids': gt_ids, \
                'texts': relation_info, 'mode': 'relation'
            })
            if summary_losses is not None:
                losses.update(summary_losses)
            if caption_losses is not None:
                losses.update(caption_losses)
            if relation_losses is not None:
                losses.update(relation_losses)
            if len(losses) == 0:
                losses.update(proposal_losses)
        return losses

    
    def _check_gt_tracks(self, gt_tracks, caption_dict):
        remove_list =[]
        for k in gt_tracks:
            if k not in caption_dict:
                remove_list.append(k)
        for k in remove_list:
            del gt_tracks[k]
        return gt_tracks


    def _post_process_tracks(self, instances, gt):
        tracks_dict = {}
        for i in range(len(instances)):
            frame_id = i + 1
            if not gt:
                feats = instances[i]['instances'].get_fields()['reid_features']
                boxes = instances[i]['instances'].get_fields()['pred_boxes'].tensor
                track_ids = instances[i]['instances'].get_fields()['track_ids']
            else:
                boxes = instances[i].get_fields()['gt_boxes'].tensor
                track_ids = instances[i].get_fields()['gt_instance_ids']
            assert boxes.shape[0] == track_ids.shape[0]
            for j in range(boxes.shape[0]):
                track_id = str(track_ids[j].item())
                if track_id not in tracks_dict:
                    tracks_dict[track_id] = {}
                tracks_dict[track_id][str(frame_id)] = {'bbox': boxes[j]}
                if not gt:
                    tracks_dict[track_id][str(frame_id)]['feat'] = feats[j]
        return tracks_dict


    def _remove_short_track(self, instances):
        ids = torch.cat([x.track_ids for x in instances], dim=0) # N
        unique_ids = ids.unique() # M
        id_inds = (unique_ids[:, None] == ids[None, :]).float() # M x N
        num_insts_track = id_inds.sum(dim=1) # M
        remove_track_id = num_insts_track < self.min_track_len # M
        unique_ids[remove_track_id] = -1
        ids = unique_ids[torch.where(id_inds.permute(1, 0))[1]]
        ids = ids.split([len(x) for x in instances])
        for k in range(len(instances)):
            instances[k] = instances[k][ids[k] >= 0]
        return instances


    def _delay_cls(self, instances, video_id):
        ids = torch.cat([x.track_ids for x in instances], dim=0) # N
        unique_ids = ids.unique() # M
        M = len(unique_ids) # #existing tracks
        id_inds = (unique_ids[:, None] == ids[None, :]).float() # M x N
        # update scores
        cls_scores = torch.cat(
            [x.cls_scores for x in instances], dim=0) # N x (C + 1)
        traj_scores = torch.mm(id_inds, cls_scores) / \
            (id_inds.sum(dim=1)[:, None] + 1e-8) # M x (C + 1)
        _, traj_inds = torch.where(id_inds.permute(1, 0)) # N
        cls_scores = traj_scores[traj_inds] # N x (C + 1)

        n_t = [len(x) for x in instances]
        boxes = [x.pred_boxes.tensor for x in instances]
        track_ids = ids.split(n_t, dim=0)
        cls_scores = cls_scores.split(n_t, dim=0)
        instances, _ = custom_fast_rcnn_inference(
            boxes, cls_scores, track_ids, [None for _ in n_t],
            [x.image_size for x in instances],
            self.roi_heads.box_predictor[-1].test_score_thresh,
            self.roi_heads.box_predictor[-1].test_nms_thresh,
            self.roi_heads.box_predictor[-1].test_topk_per_image,
            self.not_clamp_box,
        )
        for inst in instances:
            inst.track_ids = inst.track_ids + inst.pred_classes * 10000 + \
                video_id * 100000000
        return instances


    def _get_insts_with_feats(self, proposals, features):
        if self.training:
            asso_thresh = self.cfg.MODEL.ASSO_HEAD.ASSO_THRESH
        else:
            asso_thresh = self.cfg.MODEL.ASSO_HEAD.ASSO_THRESH_TEST
        fg_inds = [x.objectness_logits > asso_thresh for x in proposals]
        filtered_proposals = [x[inds] for (x, inds) in zip(proposals, fg_inds)]
        features = [features[f] for f in self.cfg.MODEL.ROI_HEADS.IN_FEATURES]
        proposal_boxes = [x.proposal_boxes for x in filtered_proposals]
        pool_features = self.asso_pooler(features, proposal_boxes)
        reid_features = self.asso_head(pool_features)
        reid_features = reid_features.view(1, -1, self.cfg.MODEL.ASSO_HEAD.FC_DIM)
        n_t = [len(x) for x in filtered_proposals]
        instances_wo_id = [inst[inds] for inst, inds in zip(proposals, fg_inds)]
        features = reid_features.view(-1, self.cfg.MODEL.ASSO_HEAD.FC_DIM).split(n_t, dim=0)
        for inst, feat in zip(instances_wo_id, features):
            inst.reid_features = feat
        pred_instances = instances_wo_id
        for p in pred_instances:
            p.pred_boxes = p.proposal_boxes
            p.scores = p.objectness_logits
            p.pred_classes = torch.zeros(
                (len(p),), dtype=torch.long, device=p.pred_boxes.device)
            p.remove('proposal_boxes')
            p.remove('objectness_logits')
        return pred_instances
    

    def _transfer_track_ids(self, gt_tracks, pred_tracks):
        id_dict = {}
        for pred_id in pred_tracks.keys():
            pred_track = pred_tracks[pred_id]
            max_iou, max_iou_id = 0, -1
            for gt_id in gt_tracks.keys():
                gt_track = gt_tracks[gt_id]
                ious, num = 0, 0
                for frame_id in pred_track.keys():
                    if frame_id not in gt_track:
                        continue
                    pred_box = pred_track[frame_id]['bbox'].cpu().numpy()
                    gt_box = gt_track[frame_id]['bbox'].cpu().numpy()
                    ious += calculate_iou(pred_box, gt_box)
                    num += 1
                if num == 0:
                    continue
                iou = ious / num
                if iou >= max_iou:
                    max_iou = iou
                    max_iou_id = gt_id
            if max_iou > 0.2:
                id_dict[pred_id] = max_iou_id
        out_pred_tracks, gt_ids = [], []
        for pred_id, pred_track in pred_tracks.items():
            if pred_id in id_dict:
                out_pred_tracks.append(pred_track)
                gt_ids.append(id_dict[pred_id])
        return out_pred_tracks, gt_ids

    
    @torch.no_grad()
    def inferene_tracks(self, batched_inputs):
        if self.training:
            self.backbone.eval()
            self.proposal_generator.eval()
        local_tracker = BYTETracker()
        video_len = len(batched_inputs)
        instances = []
        ret_instances = []
        video_features = []
        for frame_id in range(video_len):
            # instances_wo_id = self.inference(
            #     batched_inputs[frame_id: frame_id + 1], 
            #     do_postprocess=False)
            images = self.preprocess_image(batched_inputs[frame_id: frame_id + 1])
            features = self.backbone(images.tensor)
            video_features.append(features)
            proposals, _ = self.proposal_generator(images, features, None)
            instances_wo_id = self._get_insts_with_feats(proposals=proposals, features=features)            
            instances.extend([x for x in instances_wo_id])
            inst = instances[frame_id]

            dets = torch.cat([
                inst.pred_boxes.tensor, 
                inst.scores[:, None]], dim=1).cpu()
            # id_feature = inst.reid_features.cpu()
            tracks = local_tracker.update(dets)
            track_inds = [x.ind for x in tracks]
            ret_inst = inst[track_inds]
            track_ids = [x.track_id for x in tracks]
            ret_inst.track_ids = ret_inst.pred_classes.new_tensor(track_ids)
            ret_instances.append(ret_inst)
        instances = ret_instances

        if self.min_track_len > 0:
            instances = self._remove_short_track(instances)
        pred_instances = CustomRCNN._postprocess(
                instances, batched_inputs, [
                    (0, 0) for _ in range(len(batched_inputs))],
                not_clamp_box=self.not_clamp_box)
        if self.training:
            self.backbone.train()
            self.proposal_generator.train()
        return pred_instances, video_features


    def local_tracker_inference(self, batched_inputs):
        video_info = batched_inputs[-1]
        batched_inputs = batched_inputs[:-1]
        # get gt for evalutaions only
        gt_instances = [x["instances"].to(self.device) for x in batched_inputs]
        pred_instances, video_features = self.inferene_tracks(batched_inputs)
        # track finished
        pred_tracks = self._post_process_tracks(pred_instances, gt=False)
        gt_tracks = self._post_process_tracks(gt_instances, gt=True)
        gt_tracks = self._check_gt_tracks(gt_tracks, video_info['caption'])
        transfered_pred_tracks, gt_ids = self._transfer_track_ids(gt_tracks=gt_tracks, pred_tracks=pred_tracks)

        relation_info = video_info['relation']
        gt_captions = []
        for gt_id in gt_ids:
            gt_captions.append(video_info['caption'][gt_id])
        gt_summary = video_info['summary']
      
        pred_summary = self.roi_heads({'feats': video_features, 'pred_tracks': transfered_pred_tracks, 'mode': 'summary'})
        pred_captions = self.roi_heads({'pred_tracks': transfered_pred_tracks, 'mode': 'caption'})
        pred_relations = self.roi_heads({'pred_tracks': transfered_pred_tracks, 'gt_ids': gt_ids, 'texts': relation_info,'mode': 'relation'})

        if pred_relations is None:
            pred_relations = []
        else:
            pred_relations = pred_relations.cpu().tolist()

        gt_relations = []
        for i in range(len(gt_ids)):
            for j in range(len(gt_ids)):
                gt_id_i = gt_ids[i]
                gt_id_j = gt_ids[j]
                k = str(gt_id_i) + '-' + str(gt_id_j)
                if k in relation_info:
                    gt_relations.append(get_relation_labels(relation_info[k]))
        gt_relations = [gt.cpu().tolist() for gt in gt_relations]
        assert len(pred_relations) == len(gt_relations)
        
        return pred_instances, {'pred': pred_summary, 'gt': [gt_summary]}, {'pred': pred_captions, 'gt': gt_captions}, {'pred': pred_relations, 'gt': gt_relations}


def calculate_iou(box1, box2):
    # 计算交集的坐标范围
    x1_inter = max(box1[0], box2[0])
    y1_inter = max(box1[1], box2[1])
    x2_inter = min(box1[2], box2[2])
    y2_inter = min(box1[3], box2[3])

    # 计算交集的面积
    intersection_area = max(0, x2_inter - x1_inter + 1) * max(0, y2_inter - y1_inter + 1)

    # 计算并集的面积
    area_box1 = (box1[2] - box1[0] + 1) * (box1[3] - box1[1] + 1)
    area_box2 = (box2[2] - box2[0] + 1) * (box2[3] - box2[1] + 1)
    union_area = area_box1 + area_box2 - intersection_area

    # 计算交并比
    iou = intersection_area / union_area

    return iou

**Comment by zhaosonghui** [comment]
您好，您那边有没有方法可以解决上面遇到的这个问题呢？ 这个问题困扰好几天了，一直没找到解决方法。

**Comment by Nathan-Li123** [comment]
我在权重的那个one drive链接里上传了一个权重，用那个权重可以进行正常的推理，如果需要别的实验可以用那个进行。训练代码的问题我还需要寻找一下，最近在忙别的东西，我抽出时间会尽快解决一下。

**Comment by Nathan-Li123** [comment]
<img width="2149" alt="image" src="https://github.com/user-attachments/assets/cce6cafb-52bb-48eb-bfa8-6a94c63723c8">
修改convert_bensmot2coco代码应该能够解决问题，原本的代码丢失了部分数据导致没办法训练出正常的追踪模型，这样应该就可以了。我也会更新代码仓库。

**Comment by zhaosonghui** [comment]
好的谢谢！我重新一下处理一下数据试试

**Comment by zhaosonghui** [comment]
![image](https://github.com/user-attachments/assets/7789f165-4c6d-4b3c-9dc0-12532e905315)
你好，我使用更新后的代码重新处理了数据，进行训练，然而测试时候仍然为空集。

**Comment by zhaosonghui** [comment]
![image](https://github.com/user-attachments/assets/2ae28af4-ea5c-47fc-b65d-a54af080ea7b)

在训练中，各种损失都是正常的

**Comment by zhaosonghui** [comment]
> 我在权重的那个one drive链接里上传了一个权重，用那个权重可以进行正常的推理，如果需要别的实验可以用那个进行。训练代码的问题我还需要寻找一下，最近在忙别的东西，我抽出时间会尽快解决一下。

上传的这个权重文件进行测试的话会报错，可能是没有上传完整，one drive链接上传的这个pth文件为300多m，我自己训练出来的pth为1900多m大小。

**Comment by Nathan-Li123** [comment]
权重我更新了，现在是正常大小的了，试一下如果这个权重可以的话就不是推理代码的问题

**Comment by zhaosonghui** [comment]
![image](https://github.com/user-attachments/assets/27b73028-c25e-448d-baf8-60ce34e134d9)
我用今天更新的这个权重进行推理，同样返回为空集。

**Comment by zhaosonghui** [comment]
如果今天上传的权重在您那里推理测试是正常的，那感觉目前仓库里面的推理代码可能有点问题

**Comment by Nathan-Li123** [comment]
That's crazy！训练时的训练损失正常说明模型能够输出这些信息，所以训练出来的权重应该是没问题的。仓库里的代码和我目前是保持一致的，您要不再试一下pull一下看看是否哪里有变化？

**Comment by Nathan-Li123** [comment]
我又跑了一遍实验，在我这推理并没有问题
