### ISSUE TITLE
使用model_final.pth输出结果仍然为空集的问题

### ISSUE THREAD

**Issue by sove45** [Nathan-Li123/SMOTer#6]
![Screenshot from 2024-08-25 14-58-39](https://github.com/user-attachments/assets/ed0b553f-7eac-4ff4-8ccf-34b2d6ae8c33)
经过完整的训练之后,采用最终的.pth文件了来进行测试,但是最终的输出仍然为空集

测试采用的cfg文件为
_BASE_: "Base-CenterNet.yaml"
MODEL:
  META_ARCHITECTURE: "BYTERCNN"
  CENTERNET:
    USE_DEFORMABLE: True
    NMS_TH_TEST: 0.6
  ROI_HEADS:
    NAME: GRiTROIHeads
    PROPOSAL_APPEND_GT: False
    NO_BOX_HEAD: True
  WEIGHTS: '/15342518312/MOT/output/SMOTer/BYTE_BENSMOT_FPN/model_final.pth'
  ASSO_ON: True
  ASSO_HEAD:
    NEG_UNMATCHED: True
    ASSO_THRESH: 0.3
    ASSO_THRESH_TEST: 0.55
    ASSO_WEIGHT: 1.0
    NUM_WEIGHT_LAYERS: 0
    NO_POS_EMB: True
SOLVER:
  USE_CUSTOM_SOLVER: True
  MAX_ITER: 70000
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BASE_LR: 0.00005
  OPTIMIZER: ADAMW
  IMS_PER_BATCH: 4
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.1
    NORM_TYPE: 2.0
  BACKBONE_MULTIPLIER: 0.1
  # CUSTOM_MULTIPLIER: 2.0
  # CUSTOM_MULTIPLIER_NAME: ["summary_text_decoder", "classifier"]
INPUT:
  FORMAT: RGB
  CUSTOM_AUG: EfficientDetResizeCrop
  TRAIN_SIZE: 1280
  NOT_CLAMP_BOX: True
  TEST_INPUT_TYPE: square
  TEST_SIZE: 1560
  VIDEO:
    TRAIN_LEN: 100
    TEST_LEN: 100
VIDEO_INPUT: True
VIDEO_TEST:
  MAX_CENTER_DIST: 1.0
  OVERLAP_THRESH: 0.2
  DECAY_TIME: 0.9
  WITH_IOU: True
  NOT_MULT_THRESH: True
DATASETS:
  # TRAIN: ("mot17_halftrain","crowdhuman_train")
  TRAIN: ("bensmot_train",)
  TEST: ("bensmot_val",)
FIND_UNUSED_PARAM: True
DATALOADER:
  SAMPLER_TRAIN: "MultiDatasetSampler"
  SOURCE_AWARE: True
  DATASET_RATIO: [1]

**Comment by Nathan-Li123** [comment]
同样的问题，就在[Issue#5](https://github.com/Nathan-Li123/SMOTer/issues/5)中进行讨论吧
