### ISSUE TITLE
Training procedure

### ISSUE THREAD

**Issue by gabfstr** [Nathan-Li123/SMOTer#8]
Hi,
Thanks for the nice work !

I would like to reproduce the training of the model. Could you please share the config you use for the training of the first 20K iterations without the semantic heads of the model ? 
Does CH_FPN_x.pth file correspond to the weights before or after those 20K iterations ? 

Thanks in advance 
Gabriel

**Comment by Nathan-Li123** [comment]
Thanks for your attention,
During training, only one config file is required, and the approach of not training semantic heads for the first 20k iterations is implemented directly in the code.
The file CH_FPN_x.pth contains the weights needed for training initialization, and it is normal for there to be partial mismatches when training begins.

**Comment by gabfstr** [comment]
Ok, I see, thanks ! 
Where is it implemented in the code ?

**Comment by Nathan-Li123** [comment]
In byte_rcnn.py, line 144 and line 167. If your code version does not use iteration >= 20000, simply adjust it accordingly.

**Comment by gabfstr** [comment]
Ok, I see. Thanks for taking the time to answer
